sudo: required

services:
  - docker

before_install:
  - docker build -t angoca/db2-install install/10.5/expc/
  - docker build -t angoca/db2-instance instance/expc/

script:
 - echo "Successful installation"
